"""initial metadata schema

Revision ID: 0001
Revises:
Create Date: 2026-10-09 23:15:48.812223
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("taxi_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_attribution", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "analyst", "viewer", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=320), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=200), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_events_action", "audit_events", ["action"], unique=False)
    op.create_index("ix_audit_events_occurred_at", "audit_events", ["occurred_at"], unique=False)
    op.create_table(
        "data_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_key", sa.String(length=100), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("taxi_type", sa.String(length=32), nullable=False),
        sa.Column("data_period", sa.Date(), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_format", sa.String(length=16), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("raw_object_key", sa.Text(), nullable=True),
        sa.Column("source_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "registered_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "completed", "failed", "cancelled", name="job_status"),
            nullable=False,
        ),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ingestion_jobs_created_at", "ingestion_jobs", ["created_at"], unique=False)
    op.create_index("ix_ingestion_jobs_data_source_id", "ingestion_jobs", ["data_source_id"], unique=False)
    op.create_table(
        "processing_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("status", postgresql.ENUM(name="job_status", create_type=False), nullable=False),
        sa.Column("current_stage", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("stage_timings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=True),
        sa.Column("unavailable_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quality_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("spark_version", sa.String(length=32), nullable=True),
        sa.Column("curated_prefix", sa.Text(), nullable=True),
        sa.Column("quarantine_prefix", sa.Text(), nullable=True),
        sa.Column("clickhouse_rows", sa.BigInteger(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("log_events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_processing_runs_job_id", "processing_runs", ["job_id"], unique=False)
    op.create_table(
        "data_quality_metrics",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_file_count", sa.Integer(), nullable=False),
        sa.Column("input_row_count", sa.BigInteger(), nullable=False),
        sa.Column("accepted_row_count", sa.BigInteger(), nullable=False),
        sa.Column("quarantined_row_count", sa.BigInteger(), nullable=False),
        sa.Column("duplicate_row_count", sa.BigInteger(), nullable=False),
        sa.Column("missingness_by_column", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("invalid_timestamp_count", sa.BigInteger(), nullable=False),
        sa.Column("invalid_distance_count", sa.BigInteger(), nullable=False),
        sa.Column("invalid_duration_count", sa.BigInteger(), nullable=False),
        sa.Column("invalid_amount_count", sa.BigInteger(), nullable=False),
        sa.Column("unmapped_location_count", sa.BigInteger(), nullable=False),
        sa.Column("quarantine_reason_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("flag_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("input_bytes", sa.BigInteger(), nullable=False),
        sa.Column("output_bytes", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "dataset_periods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("data_period", sa.Date(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=False),
        sa.Column("min_pickup_date", sa.Date(), nullable=False),
        sa.Column("max_pickup_date", sa.Date(), nullable=False),
        sa.Column(
            "published_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "data_period", name="uq_dataset_period"),
    )
    op.create_index("ix_dataset_periods_run_id", "dataset_periods", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dataset_periods")
    op.drop_table("data_quality_metrics")
    op.drop_table("processing_runs")
    op.drop_index("ix_ingestion_jobs_created_at", table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_table("data_sources")
    op.drop_index("ix_audit_events_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_action", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("datasets")
    sa.Enum(name="job_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
