"""job queue coordination

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-10 00:07:10.113587
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingestion_jobs", sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("ingestion_jobs", sa.Column("worker_id", sa.String(length=128), nullable=True))
    op.add_column("ingestion_jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("ingestion_jobs", sa.Column("retry_of_job_id", sa.UUID(), nullable=True))
    op.create_index(
        "uq_ingestion_jobs_active_source",
        "ingestion_jobs",
        ["data_source_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_foreign_key(
        "fk_ingestion_jobs_retry_of_job_id", "ingestion_jobs", "ingestion_jobs", ["retry_of_job_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_ingestion_jobs_retry_of_job_id", "ingestion_jobs", type_="foreignkey")
    op.drop_index(
        "uq_ingestion_jobs_active_source",
        table_name="ingestion_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_column("ingestion_jobs", "retry_of_job_id")
    op.drop_column("ingestion_jobs", "heartbeat_at")
    op.drop_column("ingestion_jobs", "worker_id")
    op.drop_column("ingestion_jobs", "cancel_requested_at")
    # ### end Alembic commands ###
