"""reports and report runs

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-10 12:54:36.042814
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("template", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("visibility", sa.Enum("private", "shared", name="report_visibility"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_created_by"), "reports", ["created_by"], unique=False)
    op.create_index("ix_reports_updated_at", "reports", ["updated_at"], unique=False)
    op.create_table(
        "report_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("format", sa.Enum("pdf", "xlsx", "csv", name="report_format"), nullable=False),
        # job_status already exists (ingestion jobs); reuse it rather than create it again.
        sa.Column("status", postgresql.ENUM(name="job_status", create_type=False), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("dataset_version", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("object_key", sa.Text(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_report_runs_report_id"), "report_runs", ["report_id"], unique=False)
    op.create_index("ix_report_runs_status_created", "report_runs", ["status", "created_at"], unique=False)
    op.create_index(
        "uq_report_runs_active_format",
        "report_runs",
        ["report_id", "format"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_report_runs_active_format",
        table_name="report_runs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index("ix_report_runs_status_created", table_name="report_runs")
    op.drop_index(op.f("ix_report_runs_report_id"), table_name="report_runs")
    op.drop_table("report_runs")
    op.drop_index("ix_reports_updated_at", table_name="reports")
    op.drop_index(op.f("ix_reports_created_by"), table_name="reports")
    op.drop_table("reports")
    sa.Enum(name="report_format").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="report_visibility").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
